import type { AIModel } from './types';

export const AI_MODELS: Record<string, AIModel> = {
  'claude-sonnet': {
    id: 'claude-sonnet',
    label: 'Claude Sonnet 4',
    provider: 'claude',
    apiModelId: 'claude-sonnet-4-20250514',
    maxTokens: 8192,
    contextWindow: 200000,
    cost: { input: 3, output: 15 },
    capabilities: ['code', 'vision', 'reasoning'],
    tier: 'paid',
    dailyLimit: { type: 'tokens', value: 0, label: 'De paga' },
  },
  'claude-opus': {
    id: 'claude-opus',
    label: 'Claude Opus 4',
    provider: 'claude',
    apiModelId: 'claude-opus-4-20250514',
    maxTokens: 8192,
    contextWindow: 200000,
    cost: { input: 15, output: 75 },
    capabilities: ['code', 'vision', 'reasoning'],
    tier: 'premium',
    dailyLimit: { type: 'tokens', value: 0, label: 'De paga' },
  },
  'gpt-4o': {
    id: 'gpt-4o',
    label: 'GPT-4o',
    provider: 'openai',
    apiModelId: 'gpt-4o',
    maxTokens: 4096,
    contextWindow: 128000,
    cost: { input: 2.5, output: 10 },
    capabilities: ['code', 'vision'],
    tier: 'paid',
    dailyLimit: { type: 'tokens', value: 0, label: 'De paga' },
  },
  'gemini-2.5-flash': {
    id: 'gemini-2.5-flash',
    label: 'Gemini 2.5 Flash',
    provider: 'gemini',
    apiModelId: 'gemini-2.5-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0.075, output: 0.3 },
    capabilities: ['code', 'vision', 'reasoning'],
    tier: 'paid',
    dailyLimit: { type: 'tokens', value: 0, label: 'De paga' },
  },
  'gemini-2.5-pro': {
    id: 'gemini-2.5-pro',
    label: 'Gemini 2.5 Pro',
    provider: 'gemini',
    apiModelId: 'gemini-2.5-pro',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 1.25, output: 10 },
    capabilities: ['code', 'vision', 'reasoning'],
    tier: 'paid',
    dailyLimit: { type: 'tokens', value: 0, label: 'De paga' },
  },
  'deepseek-v3': {
    id: 'deepseek-v3',
    label: 'DeepSeek V3',
    provider: 'deepseek',
    apiModelId: 'deepseek-chat',
    maxTokens: 8192,
    contextWindow: 64000,
    cost: { input: 0.27, output: 1.1 },
    capabilities: ['code', 'reasoning'],
    tier: 'paid',
    dailyLimit: { type: 'tokens', value: 5000000, label: '5M tok gratis al registrarse' },
  },
  'deepseek-r1': {
    id: 'deepseek-r1',
    label: 'DeepSeek R1',
    provider: 'deepseek',
    apiModelId: 'deepseek-reasoner',
    maxTokens: 8192,
    contextWindow: 64000,
    cost: { input: 0.55, output: 2.19 },
    capabilities: ['code', 'reasoning'],
    tier: 'paid',
    dailyLimit: { type: 'tokens', value: 5000000, label: '5M tok gratis al registrarse' },
  },
  'deepseek-v4-flash': {
    id: 'deepseek-v4-flash',
    label: 'DeepSeek V4 Flash',
    provider: 'deepseek',
    apiModelId: 'deepseek-v4-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0.14, output: 0.28 },
    capabilities: ['code', 'reasoning'],
    tier: 'paid',
    dailyLimit: { type: 'tokens', value: 5000000, label: '5M tok gratis al registrarse' },
  },
  'deepseek-v4-pro': {
    id: 'deepseek-v4-pro',
    label: 'DeepSeek V4 Pro',
    provider: 'deepseek',
    apiModelId: 'deepseek-v4-pro',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0.435, output: 0.87 },
    capabilities: ['code', 'vision', 'reasoning'],
    tier: 'premium',
    dailyLimit: { type: 'tokens', value: 5000000, label: '5M tok gratis al registrarse' },
  },
  // ═══════════════════════════════════════
  // OPENROUTER (free tier — verified IDs)
  // ═══════════════════════════════════════
  'or-deepseek-v4-flash': {
    id: 'or-deepseek-v4-flash',
    label: 'DeepSeek V4 Flash (OR)',
    provider: 'openrouter',
    apiModelId: 'deepseek/deepseek-v4-flash:free',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 200, label: '200 req/día · 20 RPM' },
  },
  // ── OpenRouter top-tier only ──
  'or-gpt-oss-120b': {
    id: 'or-gpt-oss-120b',
    label: 'GPT-OSS 120B (OR)',
    provider: 'openrouter',
    apiModelId: 'openai/gpt-oss-120b:free',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 200, label: '200 req/día · 20 RPM' },
  },
  'or-deepseek-v4-pro': {
    id: 'or-deepseek-v4-pro',
    label: 'DeepSeek V4 Pro (OR)',
    provider: 'openrouter',
    apiModelId: 'deepseek/deepseek-v4-pro:free',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 200, label: '200 req/día · 20 RPM' },
  },
  'or-kimi-k26': {
    id: 'or-kimi-k26',
    label: 'Kimi K2.6 (OR)',
    provider: 'openrouter',
    apiModelId: 'moonshotai/kimi-k2.6:free',
    maxTokens: 8192,
    contextWindow: 200000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 200, label: '200 req/día · 20 RPM' },
  },
  'or-glm-51': {
    id: 'or-glm-51',
    label: 'GLM 5.1 (OR)',
    provider: 'openrouter',
    apiModelId: 'z-ai/glm-5.1:free',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 200, label: '200 req/día · 20 RPM' },
  },
  // ═══════════════════════════════════════
  // NVIDIA NIM (free tier — model availability changes frequently)
  // ═══════════════════════════════════════
  'nvidia-deepseek-v4-flash': {
    id: 'nvidia-deepseek-v4-flash',
    label: 'DeepSeek V4 Flash',
    provider: 'nvidia',
    apiModelId: 'deepseek-ai/deepseek-v4-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-deepseek-v4-pro': {
    id: 'nvidia-deepseek-v4-pro',
    label: 'DeepSeek V4 Pro',
    provider: 'nvidia',
    apiModelId: 'deepseek-ai/deepseek-v4-pro',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-llama-33-70b': {
    id: 'nvidia-llama-33-70b',
    label: 'Llama 3.3 70B Instruct',
    provider: 'nvidia',
    apiModelId: 'meta/llama-3.3-70b-instruct',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-llama-4-maverick': {
    id: 'nvidia-llama-4-maverick',
    label: 'Llama 4 Maverick 17B-128E',
    provider: 'nvidia',
    apiModelId: 'meta/llama-4-maverick-17b-128e-instruct',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-nemotron-super-49b-v15': {
    id: 'nvidia-nemotron-super-49b-v15',
    label: 'Nemotron Super 49B v1.5',
    provider: 'nvidia',
    apiModelId: 'nvidia/llama-3.3-nemotron-super-49b-v1.5',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-nemotron-ultra-253b': {
    id: 'nvidia-nemotron-ultra-253b',
    label: 'Nemotron Ultra 253B',
    provider: 'nvidia',
    apiModelId: 'nvidia/llama-3.1-nemotron-ultra-253b-v1',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-nemotron-3-super-120b': {
    id: 'nvidia-nemotron-3-super-120b',
    label: 'Nemotron 3 Super 120B-A12B',
    provider: 'nvidia',
    apiModelId: 'nvidia/nemotron-3-super-120b-a12b',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-nemotron-nano-3-30b': {
    id: 'nvidia-nemotron-nano-3-30b',
    label: 'Nemotron Nano 3 30B-A3B',
    provider: 'nvidia',
    apiModelId: 'nvidia/nemotron-nano-3-30b-a3b',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-mistral-large-3': {
    id: 'nvidia-mistral-large-3',
    label: 'Mistral Large 3 (675B)',
    provider: 'nvidia',
    apiModelId: 'mistralai/mistral-large-3-675b-instruct-2512',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-mistral-medium-35': {
    id: 'nvidia-mistral-medium-35',
    label: 'Mistral Medium 3.5 (128B)',
    provider: 'nvidia',
    apiModelId: 'mistralai/mistral-medium-3.5-128b',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-mistral-small-4': {
    id: 'nvidia-mistral-small-4',
    label: 'Mistral Small 4 (119B)',
    provider: 'nvidia',
    apiModelId: 'mistralai/mistral-small-4-119b-2603',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-mistral-nemotron': {
    id: 'nvidia-mistral-nemotron',
    label: 'Mistral Nemotron',
    provider: 'nvidia',
    apiModelId: 'mistralai/mistral-nemotron',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-codestral-22b': {
    id: 'nvidia-codestral-22b',
    label: 'Codestral 22B',
    provider: 'nvidia',
    apiModelId: 'mistralai/codestral-22b-instruct-v0.1',
    maxTokens: 8192,
    contextWindow: 32000,
    cost: { input: 0, output: 0 },
    capabilities: ['code'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-seed-oss-36b': {
    id: 'nvidia-seed-oss-36b',
    label: 'Seed-OSS 36B',
    provider: 'nvidia',
    apiModelId: 'bytedance/seed-oss-36b-instruct',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-gpt-oss-120b': {
    id: 'nvidia-gpt-oss-120b',
    label: 'GPT-OSS 120B',
    provider: 'nvidia',
    apiModelId: 'openai/gpt-oss-120b',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-gpt-oss-20b': {
    id: 'nvidia-gpt-oss-20b',
    label: 'GPT-OSS 20B',
    provider: 'nvidia',
    apiModelId: 'openai/gpt-oss-20b',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-glm-51': {
    id: 'nvidia-glm-51',
    label: 'GLM 5.1',
    provider: 'nvidia',
    apiModelId: 'z-ai/glm-5.1',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-minimax-m27': {
    id: 'nvidia-minimax-m27',
    label: 'MiniMax M2.7',
    provider: 'nvidia',
    apiModelId: 'minimaxai/minimax-m2.7',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-kimi-k26': {
    id: 'nvidia-kimi-k26',
    label: 'Kimi K2.6',
    provider: 'nvidia',
    apiModelId: 'moonshotai/kimi-k2.6',
    maxTokens: 8192,
    contextWindow: 200000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-step-35-flash': {
    id: 'nvidia-step-35-flash',
    label: 'Step 3.5 Flash',
    provider: 'nvidia',
    apiModelId: 'stepfun-ai/step-3.5-flash',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-llama-31-70b': {
    id: 'nvidia-llama-31-70b',
    label: 'Llama 3.1 70B Instruct',
    provider: 'nvidia',
    apiModelId: 'meta/llama-3.1-70b-instruct',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-llama-31-8b': {
    id: 'nvidia-llama-31-8b',
    label: 'Llama 3.1 8B Instruct',
    provider: 'nvidia',
    apiModelId: 'meta/llama-3.1-8b-instruct',
    maxTokens: 4096,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-mixtral-8x7b': {
    id: 'nvidia-mixtral-8x7b',
    label: 'Mixtral 8x7B Instruct',
    provider: 'nvidia',
    apiModelId: 'mistralai/mixtral-8x7b-instruct-v0.1',
    maxTokens: 8192,
    contextWindow: 32000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-phi-4-mini': {
    id: 'nvidia-phi-4-mini',
    label: 'Phi-4 Mini Instruct',
    provider: 'nvidia',
    apiModelId: 'microsoft/phi-4-mini-instruct',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },
  'nvidia-ministral-8b': {
    id: 'nvidia-ministral-8b',
    label: 'Ministral 8B',
    provider: 'nvidia',
    apiModelId: 'mistralai/ministral-8b-2501',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS · 40 RPM' },
  },

  // ═══════════════════════════════════════
  // GEMINI (free tier)
  // ═══════════════════════════════════════
  'gemini-2.5-flash-lite': {
    id: 'gemini-2.5-flash-lite',
    label: 'Gemini 2.5 Flash Lite',
    provider: 'gemini',
    apiModelId: 'gemini-2.5-flash-lite',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1500, label: '1,500 req/día · 30 RPM' },
  },
  'gemini-2-flash': {
    id: 'gemini-2-flash',
    label: 'Gemini 2 Flash',
    provider: 'gemini',
    apiModelId: 'gemini-2.0-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'vision'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1500, label: '1,500 req/día · 30 RPM' },
  },
  'gemini-2-flash-lite': {
    id: 'gemini-2-flash-lite',
    label: 'Gemini 2 Flash Lite',
    provider: 'gemini',
    apiModelId: 'gemini-2.0-flash-lite',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1500, label: '1,500 req/día · 30 RPM' },
  },
  'gemini-3.1-flash-lite': {
    id: 'gemini-3.1-flash-lite',
    label: 'Gemini 3.1 Flash Lite',
    provider: 'gemini',
    apiModelId: 'gemini-3.1-flash-lite',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1500, label: '1,500 req/día · 30 RPM' },
  },
  'gemini-3.5-flash': {
    id: 'gemini-3.5-flash',
    label: 'Gemini 3.5 Flash',
    provider: 'gemini',
    apiModelId: 'gemini-3.5-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 500, label: '500 req/día' },
  },
  'gemini-3-flash': {
    id: 'gemini-3-flash',
    label: 'Gemini 3 Flash',
    provider: 'gemini',
    apiModelId: 'gemini-3.0-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1500, label: '1,500 req/día · 30 RPM' },
  },
  'gemini-3.1-pro': {
    id: 'gemini-3.1-pro',
    label: 'Gemini 3.1 Pro',
    provider: 'gemini',
    apiModelId: 'gemini-3.1-pro',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'vision', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 50, label: '50 req/día' },
  },
};

export function getModelById(id: string): AIModel | undefined {
  return AI_MODELS[id];
}

export function getModelsByProvider(provider: string): AIModel[] {
  return Object.values(AI_MODELS).filter((m) => m.provider === provider);
}

export function getFreeModels(): AIModel[] {
  return Object.values(AI_MODELS).filter((m) => m.tier === 'free');
}
