import type { AIModel } from './types';

export const AI_MODELS: Record<string, AIModel> = {
  'claude-sonnet': {
    id: 'claude-sonnet',
    label: 'Claude Sonnet 4',
    provider: 'claude',
    apiModelId: 'claude-sonnet-4-20250514',
    maxTokens: 8192,
    contextWindow: 200000,
    cost: { input: 3, output: 15 },
    capabilities: ['code', 'vision', 'reasoning'],
    tier: 'paid',
    dailyLimit: { type: 'tokens', value: 0, label: 'De paga' },
  },
  'claude-opus': {
    id: 'claude-opus',
    label: 'Claude Opus 4',
    provider: 'claude',
    apiModelId: 'claude-opus-4-20250514',
    maxTokens: 8192,
    contextWindow: 200000,
    cost: { input: 15, output: 75 },
    capabilities: ['code', 'vision', 'reasoning'],
    tier: 'premium',
    dailyLimit: { type: 'tokens', value: 0, label: 'De paga' },
  },
  'gpt-4o': {
    id: 'gpt-4o',
    label: 'GPT-4o',
    provider: 'openai',
    apiModelId: 'gpt-4o',
    maxTokens: 4096,
    contextWindow: 128000,
    cost: { input: 2.5, output: 10 },
    capabilities: ['code', 'vision'],
    tier: 'paid',
    dailyLimit: { type: 'tokens', value: 0, label: 'De paga' },
  },
  'deepseek-v3': {
    id: 'deepseek-v3',
    label: 'DeepSeek V3',
    provider: 'deepseek',
    apiModelId: 'deepseek-chat',
    maxTokens: 8192,
    contextWindow: 64000,
    cost: { input: 0.27, output: 1.1 },
    capabilities: ['code', 'reasoning'],
    tier: 'paid',
    dailyLimit: { type: 'tokens', value: 5000000, label: '5M tok gratis al registrarse' },
  },
  'deepseek-r1': {
    id: 'deepseek-r1',
    label: 'DeepSeek R1',
    provider: 'deepseek',
    apiModelId: 'deepseek-reasoner',
    maxTokens: 8192,
    contextWindow: 64000,
    cost: { input: 0.55, output: 2.19 },
    capabilities: ['code', 'reasoning'],
    tier: 'paid',
    dailyLimit: { type: 'tokens', value: 5000000, label: '5M tok gratis al registrarse' },
  },
  'deepseek-v4-flash': {
    id: 'deepseek-v4-flash',
    label: 'DeepSeek V4 Flash',
    provider: 'deepseek',
    apiModelId: 'deepseek-v4-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0.14, output: 0.28 },
    capabilities: ['code', 'reasoning'],
    tier: 'paid',
    dailyLimit: { type: 'tokens', value: 5000000, label: '5M tok gratis al registrarse' },
  },
  'deepseek-v4-pro': {
    id: 'deepseek-v4-pro',
    label: 'DeepSeek V4 Pro',
    provider: 'deepseek',
    apiModelId: 'deepseek-v4-pro',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0.435, output: 0.87 },
    capabilities: ['code', 'reasoning'],
    tier: 'paid',
    dailyLimit: { type: 'tokens', value: 5000000, label: '5M tok gratis al registrarse' },
  },

  // ═══════════════════════════════════════
  // OPENROUTER (free tier — verified IDs)
  // ═══════════════════════════════════════
  'or-llama-33-70b': {
    id: 'or-llama-33-70b',
    label: 'Llama 3.3 70B (OR)',
    provider: 'openrouter',
    apiModelId: 'meta-llama/llama-3.3-70b-instruct:free',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 200, label: '200 req/día' },
  },
  'or-nemotron-super': {
    id: 'or-nemotron-super',
    label: 'Nemotron 3 Super 120B (OR)',
    provider: 'openrouter',
    apiModelId: 'nvidia/nemotron-3-super-120b-a12b:free',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 200, label: '200 req/día' },
  },
  'or-gpt-oss-120b': {
    id: 'or-gpt-oss-120b',
    label: 'GPT-OSS 120B (OR)',
    provider: 'openrouter',
    apiModelId: 'openai/gpt-oss-120b:free',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 200, label: '200 req/día' },
  },
  'or-qwen3-next-80b': {
    id: 'or-qwen3-next-80b',
    label: 'Qwen3 Next 80B (OR)',
    provider: 'openrouter',
    apiModelId: 'qwen/qwen3-next-80b-a3b-instruct:free',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 200, label: '200 req/día' },
  },
  'or-laguna-m1': {
    id: 'or-laguna-m1',
    label: 'Laguna M.1 (OR)',
    provider: 'openrouter',
    apiModelId: 'poolside/laguna-m.1:free',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 200, label: '200 req/día' },
  },

  // ═══════════════════════════════════════
  // NVIDIA NIM (verified from /v1/models list)
  // ═══════════════════════════════════════
  'nvidia-qwen3-coder-480b': {
    id: 'nvidia-qwen3-coder-480b',
    label: 'Qwen3-Coder 480B',
    provider: 'nvidia',
    apiModelId: 'qwen/qwen3-coder-480b-a35b-instruct',
    maxTokens: 8192,
    contextWindow: 256000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS' },
  },
  'nvidia-deepseek-v4-flash': {
    id: 'nvidia-deepseek-v4-flash',
    label: 'DeepSeek V4 Flash',
    provider: 'nvidia',
    apiModelId: 'deepseek-ai/deepseek-v4-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS' },
  },
  'nvidia-deepseek-v4-pro': {
    id: 'nvidia-deepseek-v4-pro',
    label: 'DeepSeek V4 Pro',
    provider: 'nvidia',
    apiModelId: 'deepseek-ai/deepseek-v4-pro',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS' },
  },
  'nvidia-llama-33-70b': {
    id: 'nvidia-llama-33-70b',
    label: 'Llama 3.3 70B',
    provider: 'nvidia',
    apiModelId: 'meta/llama-3.3-70b-instruct',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS' },
  },
  'nvidia-nemotron-super-49b-v15': {
    id: 'nvidia-nemotron-super-49b-v15',
    label: 'Nemotron Super 49B v1.5',
    provider: 'nvidia',
    apiModelId: 'nvidia/llama-3.3-nemotron-super-49b-v1.5',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS' },
  },
  'nvidia-codestral-22b': {
    id: 'nvidia-codestral-22b',
    label: 'Codestral 22B',
    provider: 'nvidia',
    apiModelId: 'mistralai/codestral-22b-instruct-v0.1',
    maxTokens: 8192,
    contextWindow: 32000,
    cost: { input: 0, output: 0 },
    capabilities: ['code'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS' },
  },
  'nvidia-mistral-large-3': {
    id: 'nvidia-mistral-large-3',
    label: 'Mistral Large 3',
    provider: 'nvidia',
    apiModelId: 'mistralai/mistral-large-3-675b-instruct-2512',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1000, label: 'GRATIS' },
  },
  
  // ═══════════════════════════════════════
  // GEMINI (free tier)
  // ═══════════════════════════════════════
  'gemini-3.1-pro-free': {
    id: 'gemini-3.1-pro-free',
    label: 'Gemini 3.1 Pro (Free) · Código/Razonamiento',
    provider: 'gemini',
    apiModelId: 'gemini-3.1-pro',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'vision', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 50, label: '50 req/día · Especial en Programación' },
  },
  'gemini-2.5-pro-free': {
    id: 'gemini-2.5-pro-free',
    label: 'Gemini 2.5 Pro (Free) · Código/Razonamiento',
    provider: 'gemini',
    apiModelId: 'gemini-2.5-pro',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'vision', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 50, label: '50 req/día · Especial en Programación' },
  },
  'gemma-4-31b-it-free': {
    id: 'gemma-4-31b-it-free',
    label: 'Gemma 4 31B IT (Free) · Especialista en Código',
    provider: 'gemini',
    apiModelId: 'gemma-4-31b-it',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1500, label: 'Gemma 4 · Código Puro' },
  },
  'gemma-4-26b-it-free': {
    id: 'gemma-4-26b-it-free',
    label: 'Gemma 4 26B IT (Free) · Especialista en Código',
    provider: 'gemini',
    apiModelId: 'gemma-4-26b-it',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1500, label: 'Gemma 4 · Código Puro' },
  },
  'gemini-3.5-flash-free': {
    id: 'gemini-3.5-flash-free',
    label: 'Gemini 3.5 Flash (Free) · Agente/Código Rápido',
    provider: 'gemini',
    apiModelId: 'gemini-3.5-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 500, label: '500 req/día · Rápido' },
  },
  'gemini-3-flash-free': {
    id: 'gemini-3-flash-free',
    label: 'Gemini 3 Flash (Free) · Agente/Código Rápido',
    provider: 'gemini',
    apiModelId: 'gemini-3.0-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1500, label: '1,500 req/día' },
  },
  'gemini-3.1-flash-lite-free': {
    id: 'gemini-3.1-flash-lite-free',
    label: 'Gemini 3.1 Flash Lite (Free) · Código Rápido',
    provider: 'gemini',
    apiModelId: 'gemini-3.1-flash-lite',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1500, label: '1,500 req/día · 30 RPM' },
  },
  'gemini-2.5-flash-free': {
    id: 'gemini-2.5-flash-free',
    label: 'Gemini 2.5 Flash (Free) · Código Rápido',
    provider: 'gemini',
    apiModelId: 'gemini-2.5-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'vision'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1500, label: '1,500 req/día · 30 RPM' },
  },
  'gemini-2.5-flash-lite-free': {
    id: 'gemini-2.5-flash-lite-free',
    label: 'Gemini 2.5 Flash Lite (Free) · Código Rápido',
    provider: 'gemini',
    apiModelId: 'gemini-2.5-flash-lite',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1500, label: '1,500 req/día · 30 RPM' },
  },
  'gemini-2.0-flash-free': {
    id: 'gemini-2.0-flash-free',
    label: 'Gemini 2.0 Flash (Free) · Código Rápido',
    provider: 'gemini',
    apiModelId: 'gemini-2.0-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'vision'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1500, label: '1,500 req/día · 30 RPM' },
  },
  'gemini-2.0-flash-lite-free': {
    id: 'gemini-2.0-flash-lite-free',
    label: 'Gemini 2.0 Flash Lite (Free) · Código Rápido',
    provider: 'gemini',
    apiModelId: 'gemini-2.0-flash-lite',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 1500, label: '1,500 req/día · 30 RPM' },
  },
  'gemini-1.5-pro-free': {
    id: 'gemini-1.5-pro-free',
    label: 'Gemini 1.5 Pro (Free) · Código/Razonamiento',
    provider: 'gemini',
    apiModelId: 'gemini-1.5-pro',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'vision', 'reasoning'],
    tier: 'free',
    dailyLimit: { type: 'requests', value: 50, label: '50 req/día' },
  },
  'gemini-1.5-flash-paid': {
    id: 'gemini-1.5-flash-paid',
    label: 'Gemini 1.5 Flash (Paid)',
    provider: 'gemini',
    apiModelId: 'gemini-1.5-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0.075, output: 0.3 },
    capabilities: ['code', 'vision'],
    tier: 'paid',
    dailyLimit: { type: 'tokens', value: 0, label: 'De paga' },
  },
  'gemini-1.5-pro-paid': {
    id: 'gemini-1.5-pro-paid',
    label: 'Gemini 1.5 Pro (Paid)',
    provider: 'gemini',
    apiModelId: 'gemini-1.5-pro',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 1.25, output: 10 },
    capabilities: ['code', 'vision', 'reasoning'],
    tier: 'paid',
    dailyLimit: { type: 'tokens', value: 0, label: 'De paga' },
  },
};

export function getModelById(id: string): AIModel | undefined {
  return AI_MODELS[id];
}

export function getModelsByProvider(provider: string): AIModel[] {
  return Object.values(AI_MODELS).filter((m) => m.provider === provider);
}

export function getFreeModels(): AIModel[] {
  return Object.values(AI_MODELS).filter((m) => m.tier === 'free');
}
