import type { AIModel } from './types';

export const AI_MODELS: Record<string, AIModel> = {
  'claude-sonnet': {
    id: 'claude-sonnet',
    label: 'Claude Sonnet 4',
    provider: 'claude',
    apiModelId: 'claude-sonnet-4-20250514',
    maxTokens: 8192,
    contextWindow: 200000,
    cost: { input: 3, output: 15 },
    capabilities: ['code', 'vision', 'reasoning'],
    tier: 'paid',
  },
  'claude-opus': {
    id: 'claude-opus',
    label: 'Claude Opus 4',
    provider: 'claude',
    apiModelId: 'claude-opus-4-20250514',
    maxTokens: 8192,
    contextWindow: 200000,
    cost: { input: 15, output: 75 },
    capabilities: ['code', 'vision', 'reasoning'],
    tier: 'premium',
  },
  'gpt-4o': {
    id: 'gpt-4o',
    label: 'GPT-4o',
    provider: 'openai',
    apiModelId: 'gpt-4o',
    maxTokens: 4096,
    contextWindow: 128000,
    cost: { input: 2.5, output: 10 },
    capabilities: ['code', 'vision'],
    tier: 'paid',
  },
  'gemini-2.5-flash': {
    id: 'gemini-2.5-flash',
    label: 'Gemini 2.5 Flash',
    provider: 'gemini',
    apiModelId: 'gemini-2.5-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0.075, output: 0.3 },
    capabilities: ['code', 'vision', 'reasoning'],
    tier: 'paid',
  },
  'gemini-2.5-pro': {
    id: 'gemini-2.5-pro',
    label: 'Gemini 2.5 Pro',
    provider: 'gemini',
    apiModelId: 'gemini-2.5-pro',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 1.25, output: 10 },
    capabilities: ['code', 'vision', 'reasoning'],
    tier: 'paid',
  },
  'deepseek-v3': {
    id: 'deepseek-v3',
    label: 'DeepSeek V3',
    provider: 'deepseek',
    apiModelId: 'deepseek-chat',
    maxTokens: 8192,
    contextWindow: 64000,
    cost: { input: 0.27, output: 1.1 },
    capabilities: ['code', 'reasoning'],
    tier: 'paid',
  },
  'deepseek-r1': {
    id: 'deepseek-r1',
    label: 'DeepSeek R1',
    provider: 'deepseek',
    apiModelId: 'deepseek-reasoner',
    maxTokens: 8192,
    contextWindow: 64000,
    cost: { input: 0.55, output: 2.19 },
    capabilities: ['code', 'reasoning'],
    tier: 'paid',
  },
  'or-deepseek-r1': {
    id: 'or-deepseek-r1',
    label: 'DeepSeek R1 (OR)',
    provider: 'openrouter',
    apiModelId: 'deepseek/deepseek-r1',
    maxTokens: 8192,
    contextWindow: 64000,
    cost: { input: 0.55, output: 2.19 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
  },
  'or-qwen3': {
    id: 'or-qwen3',
    label: 'Qwen3 235B (OR)',
    provider: 'openrouter',
    apiModelId: 'qwen/qwen3-235b-a22b',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0.5, output: 1.5 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
  },
  // ═══════════════════════════════════════
  // NVIDIA NIM (free tier)
  // ═══════════════════════════════════════
  'nvidia-qwen3-coder': {
    id: 'nvidia-qwen3-coder',
    label: 'Qwen3-Coder 480B-A35B',
    provider: 'nvidia',
    apiModelId: 'qwen/qwen3-coder-480b-a35b',
    maxTokens: 8192,
    contextWindow: 256000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
  },
  'nvidia-deepseek-v4-flash': {
    id: 'nvidia-deepseek-v4-flash',
    label: 'DeepSeek V4 Flash (NIM)',
    provider: 'nvidia',
    apiModelId: 'deepseek-ai/deepseek-v4-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
  },
  'nvidia-deepseek-v4-pro': {
    id: 'nvidia-deepseek-v4-pro',
    label: 'DeepSeek V4 Pro (NIM)',
    provider: 'nvidia',
    apiModelId: 'deepseek-ai/deepseek-v4-pro',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
  },
  'nvidia-mistral-small-4': {
    id: 'nvidia-mistral-small-4',
    label: 'Mistral Small 4 (119B)',
    provider: 'nvidia',
    apiModelId: 'mistralai/mistral-small-4-119b',
    maxTokens: 8192,
    contextWindow: 256000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
  },
  'nvidia-mistral-medium': {
    id: 'nvidia-mistral-medium',
    label: 'Mistral Medium 3.5 (128B)',
    provider: 'nvidia',
    apiModelId: 'mistralai/mistral-medium-3.5-128b',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
  },
  'nvidia-qwen25-coder-32b': {
    id: 'nvidia-qwen25-coder-32b',
    label: 'Qwen2.5-Coder 32B',
    provider: 'nvidia',
    apiModelId: 'qwen/qwen2.5-coder-32b-instruct',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code'],
    tier: 'free',
  },
  'nvidia-qwen3-next': {
    id: 'nvidia-qwen3-next',
    label: 'Qwen3-Next 808-A38',
    provider: 'nvidia',
    apiModelId: 'qwen/qwen3-next-808b-a38b',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
  },
  'nvidia-mistral-nemoтron': {
    id: 'nvidia-mistral-nemoтron',
    label: 'Mistral Nemotron',
    provider: 'nvidia',
    apiModelId: 'mistralai/mistral-nemotron',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
  },
  'nvidia-magistral-small': {
    id: 'nvidia-magistral-small',
    label: 'Magistral Small 2506',
    provider: 'nvidia',
    apiModelId: 'mistralai/magistral-small-2506',
    maxTokens: 8192,
    contextWindow: 32000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
  },
  'nvidia-mistral-large-3': {
    id: 'nvidia-mistral-large-3',
    label: 'Mistral Large 3 (67B)',
    provider: 'nvidia',
    apiModelId: 'mistralai/mistral-large-3-67b',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
  },
  'nvidia-minimax-m2': {
    id: 'nvidia-minimax-m2',
    label: 'MiniMax M2-7 (230B)',
    provider: 'nvidia',
    apiModelId: 'minimax/minimax-m2-7-230b',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
  },
  'nvidia-step-35-flash': {
    id: 'nvidia-step-35-flash',
    label: 'Step 3.5 Flash',
    provider: 'nvidia',
    apiModelId: 'stepfun/step-3.5-flash',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
  },
  'nvidia-seed-oss-36b': {
    id: 'nvidia-seed-oss-36b',
    label: 'Seed-OSS 36B',
    provider: 'nvidia',
    apiModelId: 'bytedance/seed-oss-36b',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
  },
  'nvidia-llama-33-70b': {
    id: 'nvidia-llama-33-70b',
    label: 'Llama 3.3 70B',
    provider: 'nvidia',
    apiModelId: 'meta/llama-3.3-70b-instruct',
    maxTokens: 8192,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
  },
  'nvidia-llama-31-8b': {
    id: 'nvidia-llama-31-8b',
    label: 'Llama 3.1 8B',
    provider: 'nvidia',
    apiModelId: 'meta/llama-3.1-8b-instruct',
    maxTokens: 4096,
    contextWindow: 128000,
    cost: { input: 0, output: 0 },
    capabilities: ['code'],
    tier: 'free',
  },

  // ═══════════════════════════════════════
  // GEMINI (free tier)
  // ═══════════════════════════════════════
  'gemini-2.5-flash-lite': {
    id: 'gemini-2.5-flash-lite',
    label: 'Gemini 2.5 Flash Lite',
    provider: 'gemini',
    apiModelId: 'gemini-2.5-flash-lite',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code'],
    tier: 'free',
  },
  'gemini-2-flash': {
    id: 'gemini-2-flash',
    label: 'Gemini 2 Flash',
    provider: 'gemini',
    apiModelId: 'gemini-2.0-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'vision'],
    tier: 'free',
  },
  'gemini-2-flash-lite': {
    id: 'gemini-2-flash-lite',
    label: 'Gemini 2 Flash Lite',
    provider: 'gemini',
    apiModelId: 'gemini-2.0-flash-lite',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code'],
    tier: 'free',
  },
  'gemini-3.1-flash-lite': {
    id: 'gemini-3.1-flash-lite',
    label: 'Gemini 3.1 Flash Lite',
    provider: 'gemini',
    apiModelId: 'gemini-3.1-flash-lite',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code'],
    tier: 'free',
  },
  'gemini-3.5-flash': {
    id: 'gemini-3.5-flash',
    label: 'Gemini 3.5 Flash',
    provider: 'gemini',
    apiModelId: 'gemini-3.5-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
  },
  'gemini-3-flash': {
    id: 'gemini-3-flash',
    label: 'Gemini 3 Flash',
    provider: 'gemini',
    apiModelId: 'gemini-3.0-flash',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'reasoning'],
    tier: 'free',
  },
  'gemini-3.1-pro': {
    id: 'gemini-3.1-pro',
    label: 'Gemini 3.1 Pro',
    provider: 'gemini',
    apiModelId: 'gemini-3.1-pro',
    maxTokens: 8192,
    contextWindow: 1000000,
    cost: { input: 0, output: 0 },
    capabilities: ['code', 'vision', 'reasoning'],
    tier: 'free',
  },
};

export function getModelById(id: string): AIModel | undefined {
  return AI_MODELS[id];
}

export function getModelsByProvider(provider: string): AIModel[] {
  return Object.values(AI_MODELS).filter((m) => m.provider === provider);
}

export function getFreeModels(): AIModel[] {
  return Object.values(AI_MODELS).filter((m) => m.tier === 'free');
}
